# Generated by Django 4.2.6 on 2024-02-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_skill_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='text',
        ),
    ]
