# Generated by Django 4.2.6 on 2024-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_skill_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(max_length=1052),
        ),
    ]
